### ISSUE TITLE
[Bug] Updated profile picture isn't displayed straight away

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1384]
Android, 2.4.15

1. Open group chat info 
2. Click Edit
3. Update the profile picture, go back to chat info 
4. The profile picture seems to be absent, it appears once you go back to the chat though

https://github.com/linagora/twake-on-matrix/assets/97684890/a08a11d2-0a34-4d7f-af88-7a9cf63615a6

**Comment by nqhhdev** [comment]
Fixed it in version 2.4.17

Pls test it again

**Comment by QuangHoang1210** [comment]
Still happen on 2.4.17 (All platform)

**Android**

https://github.com/linagora/twake-on-matrix/assets/124866146/a3bd32e5-e18f-428c-a189-8571dc8b1425

**IOS**

https://github.com/linagora/twake-on-matrix/assets/124866146/f8536768-1cb2-41b0-b2a2-73e2fb5d9e15

**WEBPC**

https://github.com/linagora/twake-on-matrix/assets/124866146/9ff56b76-b2b2-473a-b5f6-8542d65b802f
